### ISSUE TITLE
Deployed Site.

### ISSUE THREAD

**Issue by ProgramKingAbel** [ProgramKingAbel/ProgramKingAbel.github.io#1]
The app had been deployed earlier and here is the link to the live site. 

https://programkingabel.github.io/

Feel free to comment on any changes required for improvement.

**Comment by OyePriscilla** [comment]
Hi @ProgramKingAbel 👏 👏 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Website deployed using GitHub pages ✔️
Online version page works as expected ✔️

## Required Changes ♻️

- [ ] Please kindly format your `live demo` link properly, the link is redirecting me to google at the moment. 
<img width="337" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/230869880-587b1ed2-27fd-4f40-8b13-f0752962e3a9.png">

**Suggestion** `[Live link](https://programkingabel.github.io/)`

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ProgramKingAbel** [comment]
Thank you for the guidance. Done as advised

**Comment by GedeonTS** [comment]
# STATUS: APPROVED :tada: :clap: :champagne: 
Hi @ProgramKingAbel ,

You are amazing :smiley: :clap: !  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"> 

## Highlights :clap: :tophat: 
- Good job deploying with GitHub pages :+1: 
## Optional suggestions :small_airplane: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
